import re

from typer.testing import CliRunner

from integral_cli.main import app

runner = CliRunner()
ANSI_ESCAPE = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")


def _clean(text: str) -> str:
    """Remove ANSI escape sequences generated by Typer/Rich in CI/TTY environments."""
    return ANSI_ESCAPE.sub("", text)


def test_help_lists_analyse_not_analyze():
    result = runner.invoke(app, ["--help"])
    assert result.exit_code == 0
    clean = _clean(result.output)
    assert "analyse" in clean
    assert "analyze" not in clean


def test_old_analyze_spelling_is_gone():
    result = runner.invoke(app, ["analyze", "--help"])
    assert result.exit_code != 0


def test_analyse_subcommands_are_registered():
    result = runner.invoke(app, ["analyse", "--help"])
    assert result.exit_code == 0
    clean = _clean(result.output)
    for instrument in ["ibis", "jemx", "omc", "spi"]:
        assert instrument in clean


def test_analyse_ibis_help_shows_detector_and_advanced_flags():
    result = runner.invoke(app, ["analyse", "ibis", "--help"])
    assert result.exit_code == 0
    clean = _clean(result.output)
    assert "--isgri" in clean
    assert "--picsit" in clean
    assert "--compton" in clean
    assert "--og" in clean
    assert "--clean-mode" in clean
    assert "--bright-threshold" in clean
